package com.tts.ecommerce.models;

import java.util.Map;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.springframework.security.core.userdetails.UserDetails;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
//Stored in database
@Entity
public class Product {
    //primary key
    @Id
    //autogenerated primary key
    @GeneratedValue(strategy = GenerationType.AUTO)
    //name of id column used in queries
    private Long id;
    private int quantity;
    private double price;
    private String description;
    private String name;
    private String brand;
    private String category;
    private String image;
    
}